version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ec2-test-app
hooks:
  ApplicationStop:
    - location: deployment_scripts/stop_server.sh
      timeout: 300
      runas: root
      
  BeforeInstall:
    - location: deployment_scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: deployment_scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  
